### ISSUE TITLE
Streamlining and Organizing our Issue Tracker

### ISSUE THREAD

**Issue by vvatanabe** [sashabaranov/go-openai#415]
Hey @sashabaranov, thanks for running this awesome repository. I really value this open-source project and I've got a few suggestions that could help us continue its success.

I've noticed a few duplicate and unresolved (though actually resolved) issues popping up on the go-openai Issue Tracker. While they might seem like small things individually, when they start piling up, they could potentially hinder our progress with maintenance.

To tackle this problem, here are a few actions I propose:

- Let's consolidate duplicate issues to focus all conversations and solutions on a single thread.
- Once an issue has been resolved, let's close it properly to keep a clear view of the current issues.
- I suggest we add appropriate [labels](https://github.com/sashabaranov/go-openai/labels) to our issues.

Unless there are any objections, **I'm happy to get started on these tasks.**

---

**TODO:**

- [x] consolidate duplicate issues to focus all conversations and solutions on a single thread.
- [x] Once an issue has been resolved, and close it properly to keep a clear view of the current issues.
- [x] add appropriate [labels](https://github.com/sashabaranov/go-openai/labels) to our issues.
- [x] set up closing-inactive-issues in GitHub Action

**Comment by vvatanabe** [comment]
@sashabaranov I'll start implementing the proposed actions gradually. Please let me know if you have any concerns.

**Comment by vvatanabe** [comment]
I've finished labeling the open issues.

<img width="750" alt="image" src="https://github.com/sashabaranov/go-openai/assets/9883589/18527f62-e4c1-417b-afc0-8e8661fd6ccf">

Refs: https://github.com/sashabaranov/go-openai/labels

**Comment by vvatanabe** [comment]
I've closed the following issue as it has already been completed.

- [Can AudioRequest support byte array as parameter in the future?](https://github.com/sashabaranov/go-openai/issues/303)
- [Missing error processing for Audio](https://github.com/sashabaranov/go-openai/issues/300)
- [Azure OpenAI list models](https://github.com/sashabaranov/go-openai/issues/287)
- [Not as expected err: unexpected end of JSON input](https://github.com/sashabaranov/go-openai/issues/280)
- [whisper openai.AudioRequest.FilePath](https://github.com/sashabaranov/go-openai/issues/265)
- [Support multiple prompts in CompletionRequest](https://github.com/sashabaranov/go-openai/issues/84)
- [Add a Mocked Server for Testing](https://github.com/sashabaranov/go-openai/issues/30)

**Comment by vvatanabe** [comment]
I closed due to duplication with #9 on the Temperature issue.
- [How to achieve that in the same session, the results of two identical request parameters cannot be the same](https://github.com/sashabaranov/go-openai/issues/232)
- [Inconsistent results from GPT with temperature = 0](https://github.com/sashabaranov/go-openai/issues/34)

**Comment by vvatanabe** [comment]
I've closed this due to lack of comments over an extended period, even though a solution has been proposed.
- [error on Cloud Run](https://github.com/sashabaranov/go-openai/issues/279)
- [费流量](https://github.com/sashabaranov/go-openai/issues/271)
- [How to close the flow when using the following code?](https://github.com/sashabaranov/go-openai/issues/262)
- [Terminates a "stream for" loop](https://github.com/sashabaranov/go-openai/issues/251)
- [Allow headers in the proxy](https://github.com/sashabaranov/go-openai/issues/320)
- [[ERR] invalid character '<' looking for beginning of value](https://github.com/sashabaranov/go-openai/issues/233)
- [如何获取 花费的 token 数？](https://github.com/sashabaranov/go-openai/issues/231)

**Comment by vvatanabe** [comment]
I closed due to duplication with https://github.com/sashabaranov/go-openai/issues/62 on the tokenizer issue.
- [Add a method to query the remaining tokens of key](https://github.com/sashabaranov/go-openai/issues/380)
- [Ability to count tokens before sending](https://github.com/sashabaranov/go-openai/issues/200)
- [如何获取 花费的 token 数？](https://github.com/sashabaranov/go-openai/issues/231)

**Comment by sashabaranov** [comment]
@vvatanabe thank you so much, this is monumental work! What do you think about auto-closing stale issues? https://docs.github.com/en/github-ae@latest/actions/managing-issues-and-pull-requests/closing-inactive-issues

**Comment by vvatanabe** [comment]
@sashabaranov This is exactly what we've been looking for!
> For example, you can comment if an issue has been inactive for 30 days to prompt participants to take action. Then, if no additional activity occurs after 14 days, you can close the issue.

**Comment by vvatanabe** [comment]
On another note, upon triaging our issues, I've found that there's a considerable amount of 'questions'.
Shouldn't we discourage posting 'questions' as 'issues'? What about directing them towards 'discussions' or 'Stack Overflow'? This seems to be the approach adopted by many prominent open-source software projects.

**Comment by vvatanabe** [comment]
DONE
